# Generated by Django 5.2.3 on 2025-06-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('life', 'Lifestyle'), ('edu', 'Education'), ('biz', 'Business'), ('art', 'Art & Culture')], default='tech', max_length=20),
        ),
    ]
